<script>
  import TwicAbstract from '$lib/components/demo-wrapper/TwicAbstract.svelte';
  import TwicWrapper from '$lib/components/demo-wrapper/TwicWrapper.svelte';
  import Code from '$lib/components/Code.svelte';
  import { TwicVideo } from '@twicpics/components/sveltekit';
</script>

<div id="twic-short-videos-container">
  <TwicWrapper filename="src/lib/TwicShortVideos.svelte">
    <TwicAbstract title="Short Videos">
      <p>
        The ideal candidates for TwicPics video integration are hero videos, product videos, and
        thumbnails.
      </p>
      <p>
        All videos generated by the TwicPics API are muted, to be looped and played automatically.
        You can think of them as GIFs, but with high quality.
      </p>
      <p>
        The TwicVideo component automatically handles CLS, LQIP and the display of a generated
        poster until the video is actually viewable.
      </p>
      <p>
        The TwicPics API features three transformations that can be used to <a
          href="https://www.twicpics.com/docs/topics/video-optimization#video-slicing?utm_source=github&utm_medium=organic&utm_campaign=components##sveltekit"
          target="_blank"
          rel="noreferrer">extract a portion of the original video</a
        >.
      </p>
      <br />
      Here the properties used in this example:
      <ul>
        <li>
          <Code>from, to and duration</Code>:
          <span> used to extract a portion of the original video. </span>
        </li>
        <li>
          <Code>intrinsic</Code>:
          <span>prevents video upscaling and limits the number of generated variants.</span>
        </li>
        <li>
          <Code>mode</Code>:<span>determines if the image fills or sits inside the area.</span>
        </li>
        <li>
          <Code>preTransform</Code>:<span
            >allows to perfom <a
              href="https://www.twicpics.com/docs/reference/transformations?utm_source=github&utm_medium=organic&utm_campaign=components##sveltekit"
              target="_blank"
              rel="noreferrer">TwicPics API transformations</a
            >.</span
          >
        </li>
        <li>
          <Code>ratio</Code>:
          <span> determines the value of the width/height ratio of the image display area. </span>
        </li>
      </ul>
    </TwicAbstract>
    <div class="twic-grid">
      <div class="twic-item">
        <TwicVideo src="video/skater.mp4" intrinsic="1280x720" />
        <span>Default values</span>
      </div>
      <div class="twic-item">
        <TwicVideo
          src="video/skater.mp4"
          intrinsic="1280x720"
          placeholder="meancolor"
          mode="contain"
        />
        <span> ratio="1" mode="contain" </span>
      </div>
      <div class="twic-item">
        <TwicVideo src="video/skater.mp4" intrinsic="1280x720" ratio="16/9" />
        <span> ratio="16/9" </span>
      </div>
      <div class="twic-item">
        <TwicVideo src="video/skater.mp4" intrinsic="1280x720" preTransform="flip=x" />
        <span>preTransform="flip=x"</span>
      </div>
      <div class="twic-item">
        <TwicVideo src="video/skater.mp4" intrinsic="1280x720" from="15.4" />
        <span>from="15.4"</span>
      </div>
      <div class="twic-item">
        <TwicVideo src="video/skater.mp4" intrinsic="1280x720" to="16.6" />
        <span>to="16.6"</span>
      </div>
      <div class="twic-item">
        <TwicVideo src="video/skater.mp4" intrinsic="1280x720" from="15.4" to="16.6" />
        <span>from="15.4" to="16.6"</span>
      </div>
      <div class="twic-item">
        <TwicVideo src="video/skater.mp4" intrinsic="1280x720" from="15.4" duration="1.2" />
        <span>from="15.4" duration="1.2"</span>
      </div>
    </div>
  </TwicWrapper>
</div>

<style lang="scss">
  #twic-short-videos-container {
    .twic-item {
      background-color: #1fffa6;
    }
  }
</style>
